import "./globals.css";
import { GoogleOAuthProvider, GoogleLogin } from '@react-oauth/google';
import 'tailwindcss/tailwind.css';
import StoreProvider from "./store/StoreProvider";
import FetchOnLoad from "@/components/FetchOnLoad";




// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <StoreProvider>
          <FetchOnLoad />
          <GoogleOAuthProvider clientId="1060783146858-acnr84t6i0lt0u67qsjttof23gh7vuus.apps.googleusercontent.com">
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
