import "./globals.css";
import { GoogleOAuthProvider, GoogleLogin } from '@react-oauth/google';
import 'tailwindcss/tailwind.css';
import StoreProvider from "./store/StoreProvider";
import FetchOnLoad from "@/components/FetchOnLoad";
// import { ToastContainer } from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css';
import { Toaster } from 'react-hot-toast';
import HandleCart from "@/components/HandleCart";




// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <StoreProvider>
          <Toaster />
          <FetchOnLoad />
          <HandleCart />
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_OAUTH_CLIENTID}>
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
