# Generated by Django 5.0.6 on 2024-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_managers_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
