# Generated by Django 5.0.6 on 2024-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
