# Generated by Django 5.0.6 on 2024-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_categories_category_image_categories_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=20),
        ),
    ]
