# Generated by Django 5.0.6 on 2024-05-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_categories_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
