# Generated by Django 5.0.6 on 2024-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default='N/A', max_length=1000),
            preserve_default=False,
        ),
    ]
